=== Krishath/paludis-hooks/filesystem-manager/filesystem-manager.dtd
<!ELEMENT commands (package*)>
<!ATTLIST commands
    version NMTOKEN "1.5"
    xmlns CDATA #FIXED "https://github.com/zaufi/paludis-hooks/#filesystem-management-hook"
    xmlns:smh CDATA #FIXED "https://github.com/zaufi/paludis-hooks/#filesystem-management-hook"
  >

<!ELEMENT package (symlink|rm)+>
<!ATTLIST package
    descr ID #IMPLIED
    spec CDATA #REQUIRED
    stop (true|false) "false"
  >

<!ELEMENT symlink EMPTY>
<!ATTLIST symlink
    cd CDATA #REQUIRED
    src CDATA #REQUIRED
    dst CDATA #REQUIRED
  >

<!ELEMENT rm (item*)>
<!ATTLIST rm
    cd CDATA #REQUIRED
    dst CDATA #IMPLIED
  >

<!ELEMENT item EMPTY>
<!ATTLIST item
    dst CDATA #REQUIRED
  >

=== Krishath/paludis-hooks/filesystem-manager/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE commands SYSTEM "filesystem-manager.dtd">
<?xml-stylesheet type="text/xsl" href="sample.xsl"?>

<commands
    version="1.5"
    xmlns:smh="https://github.com/zaufi/paludis-hooks/#filesystem-management-hook"
    xmlns="https://github.com/zaufi/paludis-hooks/#filesystem-management-hook"
  >

    <package spec="dev-utils/cmake-2.8.9-r4:0::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake-2.8.9-r4:0">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake-2.8.9-r4::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake-2.8.9-r4">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>

    <package spec="cmake-2.8.9-r4:0::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake-2.8.9-r4:0">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake-2.8.9-r4::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}"/>
    </package>
    <package spec="cmake-2.8.9-r4">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>


    <package spec="dev-utils/cmake:0::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake:0">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/cmake">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>

    <package spec="cmake:0::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake:0">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake::zaufi-overlay">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="cmake">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>

    <package spec="dev-utils/*">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="dev-utils/*">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>

    <package spec="*/*">
        <symlink cd="/usr/share/doc" src="${PF}" dst="${PN}" />
    </package>
    <package spec="*/*">
        <rm cd="/usr/share/doc/${PF}" dst="README" />
    </package>

    <package spec="*/*" descr="man-pages-cleaner">
        <rm cd="/usr/share/man/" dst="man{0p,1,1p,2,3,3p,4,5,6,7,8}" reverse="true" />
    </package>

    <package spec="*/*" descr="docs-cleaner">
        <rm cd="/usr/share/doc/${PF}">
            <item dst="README" />
            <item dst="TODO" />
            <item dst="LICENSE" />
        </rm>
    </package>

</commands>

<!--

17  cat/package-ver-rv:slot::repo
16  cat/package-ver-rv:slot
15  cat/package-ver-rv::repo
14  cat/package-ver-rv
13  package-ver-rv:slot::repo
12  package-ver-rv:slot
11  package-ver-rv:repo
10   package-ver-rv
9   cat/package:slot::repo
8   cat/package:slot
7   cat/package::repo
6   cat/package
5   package:slot::repo
4   package:slot
3   package:repo
2   package
1   cat/*
0   */*

-->
